[metadata]
name = "C172"
version = "0.1"

[metrics]
wing_area = 16.17           # [m^2], wing reference area
wing_span = 10.97           # [m], main wing span
c_bar = 1.49                # [m], mean chord

[mass_balance]
empty_mass = 660.0          # [kg], empty operating weight
iyy = 1825.0

[mass_balance.empty_cg]     # x, y and z of the empty aircraft cg in [m]
x = 1.04
y = 0.0
z = 0.93

# Point masses in the aircaft
[[mass_balance.pointmasses]]
name = "pilot"
mass = 85.0
[mass_balance.pointmasses.location]
x = 0.91
y = -0.36
z = 0.61

[[mass_balance.pointmasses]]
name = "co-pilot"
mass = 80.0
[mass_balance.pointmasses.location]
x = 0.91
y = 0.36
z = 0.61

[[mass_balance.pointmasses]]
name = "passenger 1"
mass = 70.0
[mass_balance.pointmasses.location]
x = 1.52
y = -0.36
z = 0.61

[[mass_balance.pointmasses]]
name = "passenger 1"
mass = 70.0
[mass_balance.pointmasses.location]
x = 1.52
y = 0.36
z = 0.61

[[mass_balance.pointmasses]]
name = "luggage"
mass = 50.0
[mass_balance.pointmasses.location]
x = 2.41
y = 0.0
z = 0.61

[propulsion]

[propulsion.engine]
max_power = 160.0       # [hp], max engine power
bsfc = 0.30             # [kg/kW/hr], brake specific fuel consumption
idle_rpm = 550.0        # [1/min], idle rpm
max_rpm = 2700.0        # [1/min], max rpm
max_throttle = 1.0      # [-], max throttle setting
min_throttle = 0.1      # [-], min throttle setting

[propulsion.propeller]
ixx = 2.264             # [kg m^2], moment of inertia
diameter = 1.91         # [m], prop diameter
k_mech = 0.0            # [Nm/rad/s], mechanical drag

[propulsion.propeller.ct_curve]
J  = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 5.0]
Ct = [0.073, 0.073, 0.072, 0.071, 0.069, 0.066, 0.062, 0.055, 0.045, 0.034, 0.024, 0.013, -0.006, -0.013, -0.024, -0.034, -0.045, -0.055, -0.062, -0.066, -0.069, -0.071, -0.072, -0.073, -0.073]

[propulsion.propeller.cp_curve]
J  = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 5.0]
Cp = [0.0660, 0.0700, 0.0700, 0.0660, 0.0600, 0.0530, 0.0501, 0.0469, 0.0426, 0.0360, 0.0282, 0.0191, 0.0155, 0.0191, 0.0282, 0.0360, 0.0426, 0.0469, 0.0501, 0.0516, 0.0525, 0.0525, 0.0522, 0.0511, 0.0504, 0.0493]

[[propulsion.fuel_tank]]
capacity = 59.0         # [kg], fuel capacity in tank 1
fill_level = 1.0        # [-], fill level of the tank (0 <= fill_level <= 1)
[propulsion.fuel_tank.location]
x = 1.22
y = -2.84
z = 1.51

[[propulsion.fuel_tank]]
capacity = 59.0         # [kg], fuel capacity in tank 1
fill_level = 1.0        # [-], fill level of the tank (0 <= fill_level <= 1)
[propulsion.fuel_tank.location]
x = 1.22
y = 2.84
z = 1.51

[aerodynamics]
CL0 = 0.2921
CLde = 0.347
CLadot = 1.7
CLq = 3.9

[aerodynamics.cl_curve]
alpha = [-0.09, 0.0, 0.09, 0.1, 0.12, 0.14, 0.16, 0.17, 0.19, 0.21, 0.24, 0.26, 0.28, 0.30, 0.32, 0.34, 0.36]   # angle of attack in rad
CL = [-0.22, 0.25, 0.73, 0.83, 0.92, 1.02, 1.08, 1.13, 1.19, 1.25, 1.35, 1.44, 1.47, 1.43, 1.38, 1.30]          # CL of aircraft (wing, body, horizontal tail)